# Generated by Django 3.2.8 on 2022-01-03 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addfavourites',
            old_name='watches',
            new_name='watch',
        ),
    ]
